#!/usr/bin/env ruby

require 'json'
require 'pry-byebug'

VERSION = "crystal-speedchoice"

BLACKLISTED_LABELS = %w(
  SurfFunction.ckir_BEFORE_CHECK_FOGBADGE
  TryCutOW.ckir_BEFORE_CHECK_HIVEBADGE
  FlyFunction.ckir_BEFORE_CHECK_STORMBADGE
)

# get these, even if there's no diff
WHITELIST = %w(
  WhitneyScript_0x5400c.ckir_BEFORE_checkflag_ENGINE_PLAINBADGE
  BlackthornGymClairScript.ckir_BEFORE_checkflag_ENGINE_RISINGBADGE

  UnknownText_0x18b064.ckir_BEFORE_para_lost_your_favorite_doll
  Copycat.ckir_BEFORE_takeitem_LOST_ITEM
  Copycat.ckir_BEFORE_checkitem_LOST_ITEM
)

ORIG_JSON = ENV.fetch("ORIG_JSON", "#{VERSION}-speedchoice-labels-label-details.json")
MOD_JSON = ENV.fetch("MOD_JSON", "#{VERSION}-speedchoice-changes-label-details.json")

speedchoice_labels_json  = JSON.load(File.read(ORIG_JSON)).
  sort_by { |h| h['label'] }
speedchoice_changes_json = JSON.load(File.read(MOD_JSON)).
  sort_by { |h| h['label'] }

diff = speedchoice_labels_json.
  zip(speedchoice_changes_json).
  filter do |rl, rc|
    rl != rc || WHITELIST.include?(rl['label'])
  end.
  map do |rl, rc|
    raise <<~EOF unless rl['label'] == rc['label'] && rl['address_range'] == rc['address_range']
      #{rl['label']} != #{rc['label']}
      #{rl['address_range']} != #{rc['address_range']}
    EOF

    {
    :label => rl['label'],
    :address_range => rl['address_range'],
      :integer_values => {
        :old => rl['integer_values'].split(" ").map(&method(:Integer)),
        :new => rc['integer_values'].split(" ").map(&method(:Integer)),
      },
    }
  end.
  reject { |d| BLACKLISTED_LABELS.include?(d['label']) }.
  to_json

File.write("#{VERSION}-speedchoice-changes-diff.json", diff)
