#!/usr/bin/env ruby

require 'json'
require 'pry-byebug'

VERSION = "crystal-speedchoice"

BLACKLISTED_LABELS = %w(
  SurfFunction.ckir_BEFORE_CHECK_FOGBADGE
  TryCutOW.ckir_BEFORE_CHECK_HIVEBADGE
  FlyFunction.ckir_BEFORE_CHECK_STORMBADGE
)

ORIG_JSON = ENV.fetch("ORIG_JSON", "#{VERSION}-speedchoice-labels-v7-label-details.json")
MOD_JSON = ENV.fetch("MOD_JSON", "#{VERSION}-speedchoice-changes-v7-label-details.json")

speedchoice_labels_json  = JSON.load(File.read(ORIG_JSON)).
  sort_by { |h| h['label'] }
speedchoice_changes_json = JSON.load(File.read(MOD_JSON)).
  sort_by { |h| h['label'] }

diff = speedchoice_labels_json.
  zip(speedchoice_changes_json).
  filter { |rl, rc| rl != rc }.
  map do |rl, rc|
    raise <<~EOF unless rl['label'] == rc['label'] && rl['address_range'] == rc['address_range']
      #{rl['label']} != #{rc['label']}
      #{rl['address_range']} != #{rc['address_range']}
    EOF

    {
    :label => rl['label'],
    :address_range => rl['address_range'],
      :integer_values => {
        :old => rl['integer_values'].split(" ").map(&method(:Integer)),
        :new => rc['integer_values'].split(" ").map(&method(:Integer)),
      },
    }
  end.
  reject { |d| BLACKLISTED_LABELS.include?(d['label']) }.
  to_json

File.write("#{VERSION}-speedchoice-changes-diff.json", diff)
