#!/usr/bin/env ruby

require "json"
require "pry-byebug"

BANK_SIZE = Integer("4000", 16)

ROM_FILE = ENV.fetch("ROM_FILE", "./crystal-speedchoice.gbc")
ROM_FILE_BASENAME = File.basename(ROM_FILE, File.extname(ROM_FILE))
SYM_FILE = "#{ROM_FILE_BASENAME}.sym"
OUT_FILE = "#{ROM_FILE_BASENAME}-label-details.json"

# there's no ASM-level label for this, so we have to handle it
# specially.
ILEX_FOREST_TREE = 721295

def rom
  @rom ||= IO.binread(ROM_FILE)
end

def byte_to_string(byte)
  "$#{byte.ord.to_s(16)}"
end

def label_hex_addresses
  File
    .read(SYM_FILE)
    .split("\n")
    .select { |l| l.include?("ckir") }
    .map { |line| line.split(" ") }
    .map { |address, label| [label, address] }
end

def label_addresses
  @label_addresses ||= Hash[label_hex_addresses.map do |label, hex_address|
    bank, internal_address = hex_address.split(":").map { |val| Integer(val, 16) }
    address = (internal_address % BANK_SIZE) + (bank * BANK_SIZE)
    [label, address]
  end]
end

def rom_bytes_to_integers(rom_bytes)
  rom_bytes.split('').map(&:bytes).flatten.join(" ")
end

def ilex_forest_diff
  {
    "integer_values" => rom_bytes_to_integers(rom[ILEX_FOREST_TREE]),
    "address_range" => {
      "begin" => ILEX_FOREST_TREE,
      "end" => ILEX_FOREST_TREE + 1,
    },
    "name" => "Remove cuttable tree in Ilex Forest",
  }
end

def main
  key_item_address_ranges =
    label_addresses
      .keys
      .reject { |label| label.include?("ckir_AFTER") }
      .map do |label|
        post_label = label.gsub("ckir_BEFORE", "ckir_AFTER")
        address_range = label_addresses[label]...label_addresses[post_label]
        [label, address_range]
      end

  key_item_details =
    key_item_address_ranges.map do |key_item, address_range|
      {
        "name" => key_item,
        "address_range" => { "begin" => address_range.begin, "end" => address_range.end },
        # "values" => rom[address_range], # it's difficult to write out raw bytes :(
        "integer_values" => rom_bytes_to_integers(rom[address_range]),
        "hex_values" => rom[address_range].each_char.map(&method(:byte_to_string)).join(" "),
      }
  end.sort_by { |details| details["name"] }

  key_item_details << ilex_forest_diff

  File.write(OUT_FILE, key_item_details.to_json)

  STDERR.puts "generated #{OUT_FILE}"
end

main
