#!/usr/bin/env bash

set -eu

# make rom, generate label details and rename both
v=crystal-speedchoice

for branch in speedchoice-labels-v7 speedchoice-changes-v7; do
  git checkout $branch

  new_rom_basename=${v}-${branch}
  make ${v}.gbc
  cp ${v}.gbc ${new_rom_basename}.gbc
  cp ${v}.sym ${new_rom_basename}.sym
  ROM_FILE=${new_rom_basename}.gbc ./generate-label-details
done

./generate-randomizer-changes-diff
